arts/arts/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings 
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'arts.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^$', include('imagestore.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

# This is only needed when using runserver.
if settings.DEBUG:
    urlpatterns = patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve',  # NOQA
            {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),
        ) + staticfiles_urlpatterns() + urlpatterns  # NOQA

arts/imagestore/imagestore_cms/urls.py
#!/usr/bin/env python
# vim:fileencoding=utf-8

__author__ = 'zeus'

try:
    from django.conf.urls import include, patterns, url
except ImportError:
    from django.conf.urls.defaults import include, patterns, url

from imagestore.views import AlbumListView

urlpatterns = patterns('',
    url(r'^', include('imagestore.urls', namespace='imagestore')),
    )

arts/imagestore/urls.py
try:
    from django.conf.urls import patterns, url
except ImportError:
    from django.conf.urls.defaults import patterns, url
from .views import (AlbumListView, ImageListView, UpdateImage, UpdateAlbum, CreateImage, CreateAlbum, DeleteImage, \
                   DeleteAlbum, ImageView)


urlpatterns = patterns('imagestore.views',
                       url(r'^$', AlbumListView.as_view(), name='index'),


                       url(r'^album/add/$', CreateAlbum.as_view(), name='create-album'),
                       url(r'^album/(?P<album_id>\d+)/$', ImageListView.as_view(), name='album'),
                       url(r'^album/(?P<pk>\d+)/edit/$', UpdateAlbum.as_view(), name='update-album'),
                       url(r'^album/(?P<pk>\d+)/delete/$', DeleteAlbum.as_view(), name='delete-album'),

                       url(r'^tag/(?P<tag>[^/]+)/$', ImageListView.as_view(), name='tag'),

                       url(r'^user/(?P<username>\w+)/albums/', AlbumListView.as_view(), name='user'),
                       url(r'^user/(?P<username>\w+)/$', ImageListView.as_view(), name='user-images'),

                       url(r'^upload/$', CreateImage.as_view(), name='upload'),

                       url(r'^image/(?P<pk>\d+)/$', ImageView.as_view(), name='image'),
                       url(r'^album/(?P<album_id>\d+)/image/(?P<pk>\d+)/$', ImageView.as_view(), name='image-album'),
                       url(r'^tag/(?P<tag>[^/]+)/image/(?P<pk>\d+)/$', ImageView.as_view(), name='image-tag'),
                       url(r'^image/(?P<pk>\d+)/delete/$', DeleteImage.as_view(), name='delete-image'),
                       url(r'^image/(?P<pk>\d+)/update/$', UpdateImage.as_view(), name='update-image'),
                       )

urlpatterns += patterns('imagestore.ajax',
                       url(r'^thumbs/$', 'get_image_thumbs'),
                       url(r'^img2owner/$', 'get_image_to_owner'),
                       ) 

arts/imagestore/imagestore_cms/models.py
#!/usr/bin/env python
# vim:fileencoding=utf-8

__author__ = 'zeus'

from cms.models import CMSPlugin
from django.db import models
from imagestore.models import Album
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

class ImagestoreAlbumPtr(CMSPlugin):
    album = models.ForeignKey(Album, verbose_name=_('Album'), blank=False, null=False)

class ImagestoreAlbumCarousel(CMSPlugin):
    album = models.ForeignKey(Album, verbose_name=_('Album'), blank=False, null=False)
    skin = models.CharField(max_length=100, verbose_name=_('Skin'), default='jcarousel-skin-tango')
    limit = models.IntegerField(verbose_name=_('Image limit'), blank=True, null=True)
    size = models.CharField(max_length=20, verbose_name=_('Thumbnail size'), default='72x72')
    full_size = models.CharField(max_length=20, verbose_name=_('Full size view'), default='600x600')
    template_file = models.CharField(max_length=100, verbose_name=_('Template file'), default=getattr(settings,'IMAGESTORE_CAROUSEL_TEMPLATE','cms/plugins/imagestore_album_carousel.html'), blank=True, null=True)

arts/imagestore/models/album.py
#!/usr/bin/env python
# vim:fileencoding=utf-8

__author__ = 'zeus'

from .bases.album import BaseAlbum
from django.utils.translation import ugettext_lazy as _
from imagestore.utils import load_class, get_model_string

class Album(BaseAlbum):

    class Meta(BaseAlbum.Meta):
        abstract = False
        verbose_name = _('Album')
        verbose_name_plural = _('Albums')
        app_label = 'imagestore'

arts/imagestore/models/image.py
#!/usr/bin/env python
# vim:fileencoding=utf-8

__author__ = 'zeus'

from .bases.image import BaseImage
from django.utils.translation import ugettext_lazy as _
from imagestore.utils import load_class, get_model_string

class Image(BaseImage):
    class Meta(BaseImage.Meta):
        abstract = False
        verbose_name = _('Image')
        verbose_name_plural = _('Images')
        app_label = 'imagestore'

arts/imagestore/views.py
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.utils.decorators import method_decorator
from imagestore.models import Album, Image
from imagestore.models import image_applabel, image_classname
from imagestore.models import album_applabel, album_classname
from django.shortcuts import get_object_or_404
from django.http import Http404, HttpResponseRedirect
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.decorators import login_required
from django.utils.translation import ugettext_lazy as _
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from tagging.models import TaggedItem
from tagging.utils import get_tag

from .utils import load_class

try:
    from django.contrib.auth import get_user_model
    User = get_user_model()
    username_field = User.USERNAME_FIELD
except ImportError:
    from django.contrib.auth.models import User
    username_field = 'username'

IMAGESTORE_IMAGES_ON_PAGE = getattr(settings, 'IMAGESTORE_IMAGES_ON_PAGE', 20)

IMAGESTORE_ON_PAGE = getattr(settings, 'IMAGESTORE_ON_PAGE', 20)

ImageForm = load_class(getattr(settings, 'IMAGESTORE_IMAGE_FORM', 'imagestore.forms.ImageForm'))
AlbumForm = load_class(getattr(settings, 'IMAGESTORE_ALBUM_FORM', 'imagestore.forms.AlbumForm'))


class AlbumListView(ListView):
    context_object_name = 'album_list'
    template_name = 'imagestore/album_list.html'
    paginate_by = getattr(settings, 'IMAGESTORE_ALBUMS_ON_PAGE', 20)
    allow_empty = True

    def get_queryset(self):
        albums = Album.objects.filter(is_public=True).select_related('head')
        self.e_context = dict()
        if 'username' in self.kwargs:
            user = get_object_or_404(**{'klass': User, username_field: self.kwargs['username']})
            albums = albums.filter(user=user)
            self.e_context['view_user'] = user
        return albums

    def get_context_data(self, **kwargs):
        context = super(AlbumListView, self).get_context_data(**kwargs)
        context.update(self.e_context)
        return context


def get_images_queryset(self):
    images = Image.objects.all()
    self.e_context = dict()
    if 'tag' in self.kwargs:
        tag_instance = get_tag(self.kwargs['tag'])
        if tag_instance is None:
            raise Http404(_('No Tag found matching "%s".') % self.kwargs['tag'])
        self.e_context['tag'] = tag_instance
        images = TaggedItem.objects.get_by_model(images, tag_instance)
    if 'username' in self.kwargs:
        user = get_object_or_404(**{'klass': User, username_field: self.kwargs['username']})
        self.e_context['view_user'] = user
        images = images.filter(user=user)
    if 'album_id' in self.kwargs:
        album = get_object_or_404(Album, id=self.kwargs['album_id'])
        self.e_context['album'] = album
        images = images.filter(albums=album)
        if (not album.is_public) and\
           (self.request.user != album.user) and\
           (not self.request.user.has_perm('imagestore.moderate_albums')):
            raise PermissionDenied
    return images


class ImageListView(ListView):
    context_object_name = 'image_list'
    template_name = 'imagestore/image_list.html'
    paginate_by = getattr(settings, 'IMAGESTORE_IMAGES_ON_PAGE', 20)
    allow_empty = True

    get_queryset = get_images_queryset

    def get_context_data(self, **kwargs):
        context = super(ImageListView, self).get_context_data(**kwargs)
        context.update(self.e_context)
        return context


class ImageView(DetailView):
    context_object_name = 'image'
    template_name = 'imagestore/image.html'

    get_queryset = get_images_queryset

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        album = self.object.albums.get(pk=kwargs['album_id'])
        if album:
            if (not album.is_public) and\
            (self.request.user != album.user) and\
            (not self.request.user.has_perm('imagestore.moderate_albums')):
                raise PermissionDenied

        context = self.get_context_data(object=self.object, album=album)
        return self.render_to_response(context)

    def get_context_data(self, **kwargs):
        context = super(ImageView, self).get_context_data(**kwargs)

        image = context['image']
        album = context['album']
        albumimage = image.albumimage_set.get(album=album, image=image)

        base_qs = self.get_queryset()
        count = base_qs.count()

        img_pos = base_qs.filter(
            Q(albumimage__album_id=album.pk,
              albumimage__order__lt=albumimage.order)|
            Q(albumimage__album_id=album.pk,
              id__lt=image.id, albumimage__order=albumimage.order)
        ).count()

        next = None
        previous = None
        if count - 1 > img_pos:
            try:
                next = base_qs.filter(
                    Q(albumimage__album_id=album.pk,
                      albumimage__order__gt=albumimage.order)|
                    Q(albumimage__album_id=album.pk,
                      id__gt=image.id, albumimage__order=albumimage.order)
                ).order_by('albumimage__order', 'id')[0]
            except IndexError:
                pass
        if img_pos > 0:
            try:
                previous = base_qs.filter(
                    Q(albumimage__album_id=album.pk,
                      albumimage__order__lt=albumimage.order)|
                    Q(albumimage__album_id=album.pk,
                      id__lt=image.id, albumimage__order=albumimage.order)
                ).order_by('-albumimage__order', '-id')[0]
            except IndexError:
                pass
        context['next'] = next
        context['previous'] = previous
        context.update(self.e_context)
        return context


class CreateAlbum(CreateView):
    template_name = 'imagestore/forms/album_form.html'
    model = Album
    form_class = AlbumForm

    @method_decorator(login_required)
    @method_decorator(permission_required('%s.add_%s' % (album_applabel, album_classname)))
    def dispatch(self, *args, **kwargs):
        return super(CreateAlbum, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


def filter_album_queryset(self):
    if self.request.user.has_perm('imagestore.moderate_albums'):
        return Album.objects.all()
    else:
        return Album.objects.filter(user=self.request.user)


class UpdateAlbum(UpdateView):
    template_name = 'imagestore/forms/album_form.html'
    model = Album
    form_class = AlbumForm

    get_queryset = filter_album_queryset

    @method_decorator(login_required)
    @method_decorator(permission_required('%s.add_%s' % (album_applabel, album_classname)))
    def dispatch(self, *args, **kwargs):
        return super(UpdateAlbum, self).dispatch(*args, **kwargs)


class DeleteAlbum(DeleteView):
    template_name = 'imagestore/album_delete.html'
    model = Album

    def get_success_url(self):
        return reverse('imagestore:index')

    get_queryset = filter_album_queryset

    @method_decorator(login_required)
    @method_decorator(permission_required('%s.change_%s' % (album_applabel, album_classname)))
    def dispatch(self, *args, **kwargs):
        return super(DeleteAlbum, self).dispatch(*args, **kwargs)


class CreateImage(CreateView):
    template_name = 'imagestore/forms/image_form.html'
    model = Image
    form_class = ImageForm

    @method_decorator(login_required)
    @method_decorator(permission_required('%s.add_%s' % (image_applabel, image_classname)))
    def dispatch(self, *args, **kwargs):
        return super(CreateImage, self).dispatch(*args, **kwargs)

    def get_form(self, form_class):
        return form_class(user=self.request.user, **self.get_form_kwargs())

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        if self.object.album:
            self.object.album.save()
        return HttpResponseRedirect(self.get_success_url())


def get_edit_image_queryset(self):
    if self.request.user.has_perm('%s.moderate_%s' % (image_applabel, image_classname)):
        return Image.objects.all()
    else:
        return Image.objects.filter(user=self.request.user)


class UpdateImage(UpdateView):
    template_name = 'imagestore/forms/image_form.html'
    model = Image
    form_class = ImageForm

    get_queryset = get_edit_image_queryset

    def get_form(self, form_class):
        return form_class(user=self.object.user, **self.get_form_kwargs())

    @method_decorator(login_required)
    @method_decorator(permission_required('%s.change_%s' % (image_applabel, image_classname)))
    def dispatch(self, *args, **kwargs):
        return super(UpdateImage, self).dispatch(*args, **kwargs)


class DeleteImage(DeleteView):
    template_name = 'imagestore/image_delete.html'
    model = Image

    def get_success_url(self):
        return reverse('imagestore:index')

    get_queryset = get_edit_image_queryset

    @method_decorator(login_required)
    @method_decorator(permission_required('%s.delete_%s' % (image_applabel, image_classname)))
    def dispatch(self, *args, **kwargs):
        return super(DeleteImage, self).dispatch(*args, **kwargs)

arts/imagestore/templates/imagestore/album_delete.html
{% extends "imagestore/base.html" %}

{% load i18n %}

{% block content %}
    <p>{% trans "Are you sure that you would like to delete this album?" %}</p>
    <form method="post" action=".">
        {% csrf_token %}
        <p>
            <a class='btn' href="{{ post.get_absolute_url }}">← {% trans "No, take me back" %}</a>
            <input type="submit" class='btn danger' value="{% trans 'Yes, I am sure' %}" />
        </p>
    </form>
{% endblock %}

arts/imagestore/templates/imagestore/album_list.html
{% extends "imagestore/base.html" %}
{% load i18n %}
{% load thumbnail %}

{% block title %}
    {% if view_user %}
        {% trans "Albums for user" %} {{ view_user }}
    {% else %}
        {% trans "All albums" %}
    {% endif %}
{% endblock %}

{% block imagestore-breadcrumb %}
    <li>
        {% if view_user %}
            {% trans "Albums for user" %} {{ view_user }}
        {% else %}
            {% trans "All albums" %}
        {% endif %}
    </li>
{% endblock %}

{% block imagestore-info %}
    {% if view_user and IMAGESTORE_SHOW_USER %}
        {% with user=view_user %}
            {% include "imagestore/user_info.html" %}
        {% endwith %}
    {% endif %}
{% endblock %}

{% block imagestore-related %}
    {% include "imagestore/tag-cloud.html" %}
{% endblock %}

{% block content %}
    <h1>{% if view_user %}
        {% trans "Albums for user" %} {{ view_user }}
    {% else %}
        {% trans "All albums" %}
    {% endif %}</h1>
    {% include "imagestore/pagination.html" %}
    <div class='album-list'>
        {% for album in album_list %}
            {% if album.get_head  or album.user == request.user %}
            <div class='album'>
                <div class='album-head'>
                    <a href="{{ album.get_absolute_url }}">
                    {% if album.get_head %}
                        {% thumbnail album.get_head.image "150x150" crop='center' as album_head %}
                            <img class="preview" {% if album.name %} alt="{{ album.name }}" {% endif %} src="{{ album_head.url }}">
                        {% endthumbnail %}
                    {% else %}
                        [{% trans "Empty album" %}]
                    {% endif %}
                    <br>
                    <span class="album-name">{{ album.name }}</span>
                    {% if not view_user and IMAGESTORE_SHOW_USER %}
                        <br>
                        <span class="album-user">
                            {% trans "user" %}: {{ album.user }}
                        </span>
                    {% endif %}
                    </a>
                </div>
            </div>
            {% endif %}
        {% endfor %}
    </div>
    {% include "imagestore/pagination.html" %}
{% endblock %}

arts/imagestore/templates/imagestore/base.html
{% extends IMAGESTORE_TEMPLATE|default:"base.html" %}
{% load i18n %}
{% load url from future %}

{% block head %}
    {% if IMAGESTORE_LOAD_CSS %}
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}imagestore.css" media="screen" />
    {% endif %}
{% endblock %}

{% block breadcrumb %}
    <ul class='breadcrumb'>
        {% if request.path != '/' %}
            <li><a href="/">{% trans "Home" %}</a> <span class="divider">/</span></li>
        {% endif %}
        {% if request.path != imagestore_index_url %}
            <li><a href="{{ imagestore_index_url }}">{% trans "Gallery" %}</a> <span class="divider">/</span></li>
        {% endif %}
        {% block imagestore-breadcrumb %}
    {% endblock %}
    </ul>
{% endblock %}

{% block content %}
{% endblock content %}

{% block content-related %}
        {% block imagestore-info %}
        {% endblock %}
        <div id="controls">
            <ul>
                {% if imagestore_perms.add_image or request.user.is_superuser %}
                    <li><a href={% url 'imagestore:upload' %}>{% trans "Upload image" %}</a></li>
                {% endif %}
                {% if imagestore_perms.add_album or request.user.is_superuser %}
                    <li><a href={% url 'imagestore:create-album' %}>{% trans "Create new album" %}</a></li>
                {% endif %}
                {% block controls %}
                {% endblock controls %}
            </ul>
        </div>
        {% block imagestore-related %}
        {% endblock %}
{% endblock %}

arts/imagestore/templates/imagestore/image-href.html
{% load url from future %}
{% if album %}
    {% url 'imagestore:image-album' album_id=album.id pk=image.id %}
{% else %}
    {% if tag %}
        {% url 'imagestore:image-tag' tag=tag pk=image.id %}
    {% else %}
        {{ image.get_absolute_url }}
    {% endif %}
{% endif %}

arts/imagestore/templates/imagestore/image-list.html
{% load i18n %}
{% load thumbnail %}

<div id="image-thumbnails">
    {% for image in image_list %}
        {% thumbnail image.image "120x120" crop="center" as im %}
            <a class="thumb" rel='gallery-image[ilist]' href="{{ image.image.url }}">
                <img class="preview" {% if image.title %} alt="{{ image.title }}" {% endif %} src="{{ im.url }}">
            </a>
            <a href="{% url '{{ image.get_absolute_url }}' %}">
                {% if image.title %}
                    <br><span class='image-title'>{{ image.title }}</span>
                {% else %}
                    {% trans 'Info' %}
                {% endif %}
            </a>
        {% endthumbnail %}
    {% endfor %}
    {% include "imagestore/pagination.html" %}
</div>

arts/imagestore/templates/imagestore/image-scope.html
{% load i18n %}
{% if view_user %}
    {% if scope_tag %}<{{ scope_tag }} class='scope-view-user'>{% endif %}
        {% trans "User" %}: {{ view_user }}
    {% if scope_tag %}</{{ scope_tag }}>{% endif %}
{% endif %}
{% if album %}
    {% if scope_tag %}<{{ scope_tag }} class='scope-album'>{% endif %}
        {% trans "Album" %}: {{ album.name }}
    {% if scope_tag %}</{{ scope_tag }}>{% endif %}
{% endif %}
{% if tag %}
    {% if scope_tag %}<{{ scope_tag }} class='scope-album'>{% endif %}
    {% trans "Tag" %}: {{ tag }}
    {% if scope_tag %}</{{ scope_tag }}>{% endif %}
{% endif %}

arts/imagestore/templates/imagestore/image.html
{% extends "imagestore/base.html" %}
{% load i18n %}
{% load thumbnail %}
{% load tagging_tags %}
{% load url from future %}

{% block title %}
    {% trans "Image" %} - {{ image.title }}
{% endblock %}

{% block imagestore-breadcrumb %}
    {% if view_user and IMAGESTORE_SHOW_USER %}
        <li class='scope-view-user'><a href="{% url 'imagestore:user-images' username=view_user %}">{% trans "User" %}: {{ view_user }}</a> <span class="divider">/</span></li>
    {% endif %}
    {% if album %}
        <li class='scope-album'><a href="{{ album.get_absolute_url }}">{% trans "Album" %}: {{ album.name }}</a> <span class="divider">/</span></li>
    {% endif %}
    {% if tag %}
        <li class='scope-tag'><a href="{% url 'imagestore:tag' tag=tag %}">{% trans "Tag" %}: {{ tag }}</a> <span class="divider">/</span></li>
    {% endif %}
    <li>
        {% if image.title %}
            {{ image.title }}
        {% else %}
            {{ image.id }}
        {% endif %}
    </li>
{% endblock %}

{% block imagestore-info %}
    <div class='user-info'>
    {% if IMAGESTORE_SHOW_USER %}
        {% with user=image.user %}
            {% include "imagestore/user_info.html" %}
        {% endwith %}
    {% endif %}
    </div>
{% endblock %}

{% block content %}
        {% if image.title %}<h1>{{ image.title }}</h1>{% endif %}
        {% if album or tag or view_user %}
            <h2>
                    {% include "imagestore/image-scope.html" %}
            </h2>
        {% endif %}
        <div class="image-description">
            {{ image.description }}
        </div>
        <div id="image-view">
            <div class="navigation">
                {% if previous %} <a class="previous-link" href="
                {% with previous as image %}
                    {% include "imagestore/image-href.html" %}
                {% endwith %}
                ">← {% trans "previous image" %}</a> {% endif %}
                {% if next %} <a class="next-link" href="{% with next as image %}
                    {% include "imagestore/image-href.html" %}
                {% endwith %}">{% trans "next image" %} →</a> {% endif %}
            </div>
            {% thumbnail image.image "800x800" as full_im %}
                <img class="preview" {% if image.title %} alt="{{ image.title }}" {% endif %} src="{{ full_im.url }}">
            {% endthumbnail %}
        </div>
{% endblock content %}

{% block controls %}
    {% if request.user == image.user or perms.imagestore.moderate_images %}
        <li><a href="{% url 'imagestore:update-image' image.id %}">{% trans "Edit info" %}</a></li>
        <li><a href="{% url 'imagestore:delete-image' image.id %}">{% trans "Delete image" %}</a></li>
    {% endif %}
{% endblock %}

{% block imagestore-related %}

     <div class="tagging">
            <h2>{% trans "Tags" %}</h2>
            {% tags_for_object image as itags %}
            {% for tag in itags %}
                <a href="{% url 'imagestore:tag' tag.name %}">{{ tag.name }}</a>
            {% endfor %}
     </div>
     {% if image.place %}
         <div class='place'>
            <h2>{% trans "Place" %}</h2>
            <a href="{{ image.place.get_absolute_url }}">{{ image.place.name }} →</a>
         </div>
     {% endif %}
{% endblock %}

arts/imagestore/templates/imagestore/image_confirm_delete.html
{% extends "imagestore/base.html" %}

{% load i18n %}

{% block content %}
    <p>{% trans "Are you sure that you would like to delete this image?" %}</p>
    <form method="post" action=".">
        {% csrf_token %}
        <p>
            <a class='btn' href="{{ post.get_absolute_url }}">← {% trans "No, take me back" %}</a>
            <input type="submit" class='btn danger' value="{% trans 'Yes, I am sure' %}" />
        </p>
    </form>
{% endblock %}

arts/imagestore/templates/imagestore/image_delete.html
{% extends "imagestore/base.html" %}

{% load i18n %}

{% block content %}
    <p>{% trans "Are you sure that you would like to delete this image?" %}</p>
    <form method="post" action=".">
        {% csrf_token %}
        <p>
            <a class='btn' href="{{ post.get_absolute_url }}">← {% trans "No, take me back" %}</a>
            <input type="submit" class='btn danger' value="{% trans 'Yes, I am sure' %}" />
        </p>
    </form>
{% endblock %}

arts/imagestore/templates/imagestore/image_list.html
{% extends "imagestore/base.html" %}
{% load i18n %}
{% load thumbnail %}
{% load url from future %}

{% block imagestore-breadcrumb %}
    {% with "li" as scope_tag %}
        {% include "imagestore/image-scope.html" %}
    {% endwith %}
{% endblock %}

{% block title %}
    {% include "imagestore/image-scope.html" %}
{% endblock %}

{% block imagestore-info %}
    {% if view_user and IMAGESTORE_SHOW_USER %}
        {% with user=view_user %}
            {% include "imagestore/user_info.html" %}
        {% endwith %}
    {% endif %}
    {% if album and IMAGESTORE_SHOW_USER %}
        {% with user=album.user %}
            {% include "imagestore/user_info.html" %}
        {% endwith %}
    {% endif %}

{% endblock %}


{% block controls %}
    {% if album %}
        {% if request.user == album.user or perms.imagestore.moderate_albums %}
            <li><a href='{% url 'imagestore:update-album' pk=album.pk %}'>{% trans "Edit album" %}</a></li>
        {% endif %}
    {% endif %}
{% endblock %}

{% block content %}
    <h1>
        {% include "imagestore/image-scope.html" %}
    </h1>
    {% include "imagestore/pagination.html" %}
    <div id="image-thumbnails">
        {% for image in image_list %}
            <div class='image-preview'>
            {% thumbnail image.image "120x120" crop="center" as im %}
                <a class="thumb" rel='gallery-image[ilist]' href="{{ image.image.url }}">
                    <img class="preview" {% if image.title %} alt="{{ image.title }}" {% endif %} src="{{ im.url }}">
                </a>
                <a href="{% include "imagestore/image-href.html" %}">
                    {% if image.title %}
                        <br><span class='image-title'>{{ image.title }}</span>
                    {% else %}
                        {% trans 'Info' %}
                    {% endif %}
                </a>
            {% endthumbnail %}
            </div>
        {% endfor %}
    </div>
    {% include "imagestore/pagination.html" %}
{% endblock %}

arts/imagestore/templates/imagestore/pphoto.html
<link rel="stylesheet" href="{{ STATIC_URL }}prettyphoto/css/prettyPhoto.css" type="text/css" media="screen" charset="utf-8" />
<script src="{{ STATIC_URL }}prettyphoto/js/jquery.prettyPhoto.js" type="text/javascript" charset="utf-8"></script>

<script type="text/javascript" charset="utf-8">
    var prettyparams = {
        animation_speed: 'fast',
        slideshow: 3000,
        autoplay_slideshow: false,
        opacity: 0.7,
        show_title: true,
        allow_resize: true,
        default_width: 1000,
        default_height: 344,
        counter_separator_label: '/',
        theme: 'facebook',
        overlay_gallery: true,
        changepicturecallback: function() {$pp_overlay.css({'height':$(document).height()})},
        };
    $(function(){$("a[rel^='gallery-image']").prettyPhoto(prettyparams)});
</script>

arts/imagestore/templates/imagestore/tag-cloud.html
{% load tagging_tags %}
{% load i18n %}
{% load url from future %}

{% if IMAGESTORE_SHOW_TAGS %}
    <div id="tag-cloud">
        <h1>{% trans "Tags" %}</h1>
        {% tag_cloud_for_model imagestore.Image as image_tags %}
        {% for tag in image_tags %}
            <a href={% url 'imagestore:tag' tag.name %}>{{ tag.name }}</a>
        {% endfor %}
    </div>
{% endif %}